### ISSUE TITLE
add resources on buddhism

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge-map#302]
Which cannot already be found [here](https://my.mindnode.com/PHeBsyHD839v5iix1qB36PwaQjkLhYW7w6ttvpx6)

**Comment by jonfujita** [comment]
Hi, I am a student of Buddhism and I am learning to code. There are hundreds of resources available for the topic, but I want to make sure I am helping you in the right way. I'd be interested in knowing more about your strategy for building this visual search engine, and your criteria for including certain resources.

**Comment by nikitavoloboev** [comment]
Hi @jonfujita 

Thank you a lot for taking a look at this and wanting to help. You are actually the first one to do so. 💙

My current criteria is to just collect valuable resources on the topic where 'valuable' means anything that brings information on the topic and helps both introduce a person to the subject or help deepen understanding of it. Articles, courses or any other informational resource is great.

Currently though I want to focus on [study plans](https://github.com/nikitavoloboev/knowledge-map/tree/master/learning-mindmaps)  which should give step by step instructions on how to be introduced to a subject. I [opened an issue for buddhism too](https://github.com/nikitavoloboev/knowledge-map/issues/425).

For example I only briefly know about buddhism and its philosophy outside of reading of wikipedia and reading Alan Watts. What do you think is the best way to be introduced to the subject? I put buddhism under 'mindfulness' as I think that is appropriate.

**Comment by jonfujita** [comment]
Thanks for your reply. It is good to know I can support projects like yours in an open way. To put it in computer science terms, Buddhism has a superclass relationship to other traditions like mindfulness. I'm a Pythoner, so I'll put it [this](https://github.com/jonfujita/buddhism_in_OOP/blob/master/prelim_structure.py) way. I hope you find it helpful.
