### ISSUE TITLE
addtition to protocols

### ISSUE THREAD

**Issue by narosu** [nikitavoloboev/knowledge-map#487]
There are a lot of protocols missing. I think it would be too much if you add all of them, but maybe you can add the 'common' ones: https://en.wikibooks.org/wiki/Network_Plus_Certification/Technologies/Common_Protocols

What is also important, is the OSI model. A 7-layer model which characterizes the networking structures: https://en.wikipedia.org/wiki/OSI_model
Every single protocol can also be assigned to a specific layer.

So you could put the node 'tcp/ip' under 'protocols', add nodes for every layer and below nodes for the protocols, or just a node for the OSI model, or something like that :)

**Comment by nikitavoloboev** [comment]
Yeah there is certainly many protocols that are missing. Thank you a lot for your feedback, I will add the OSI model and the most common protocols. Not fully sure how to structure it well though.

**Comment by deltaidea** [comment]
That's really going deep into the details though, compared to, say, how physics is mapped out.

What's the guideline here: branch into little implementation details or leave it to Wikipedia and blogs and stuff?

**Comment by nikitavoloboev** [comment]
The focus is really to not hold content but hold links to content and organise it in a smart visual way. I also focus on providing step by step most efficient path you can take for learning any of the topics as indicated with '1.' '2.' .. numbering.

Mostly I want to focus on covering the most important topics and providing the best resources available related to it and then you can try and branch out and try and map concepts and terms together similar to what I am attempting to do in the [research](https://my.mindnode.com/P2WTfATNrnsxm23L7jQMotnJhzeh41sWWH2jgZzU#-36.3,-44.2,0) mind map.

**Comment by nikitavoloboev** [comment]
And I agree with @deltaidea that mapping protocols to such detail is not representative of what is going on in other mind maps. I think the way '[math](explore/math/math.md)' and '[physics](explore/physics/physics.md)' mind maps are structured is done quite well and how I want to approach mapping content. High level picture and concepts first, details later.
