### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Epistol** [nikitavoloboev/knowledge-map#601]
Hi,

This project look great !

What a good idea to mind map content and idea together. But still, everything available is in english, which is not a good thing for foreign languages.

Do you plan to let people switch to another one ?

**Comment by nikitavoloboev** [comment]
That would take enormous amount of effort unless one can automate it in some way and google translate all of the nodes. I think all nodes contain only english content too. 

There is a mind map for learning [english language](https://my.mindnode.com/oTrSaQmHmUvsfe1y2CpKU4xxnXueJKpKGoyWLZ68) although it only gives one resource there. Would love to add more though in time.

Glad you like the project.

**Comment by Epistol** [comment]
Thank for your quick answer 👍 

I agree with you with the time to pass on it to translate but I do think that every country / language their own content and been ego centred on English one is not good for sharing.
