### ISSUE TITLE
best path for studying philosophy

### ISSUE THREAD

**Issue by truongminh** [nikitavoloboev/knowledge-map#643]
Is there anybody recommending some basic materials?

**Comment by nikitavoloboev** [comment]
Here is a mind map for [Philosophy](https://my.mindnode.com/DaLRfu3ipMHEkhxuzqKTgbZPLmVGTmN7khBS3xqZ#-28.4,-144.3,2). I try to use these issues for adding content to the mind map. We do have a [slack group](https://knowledge-map.slack.com/shared_invite/MTgxNTYzMjIzNjM5LTE0OTQzMzA4MDAtYzY1YWY0ZDc0NQ) you can join and there you can make a study group.

**Comment by truongminh** [comment]
great resource and studying direction, thank @nikitavoloboev
