### ISSUE TITLE
Fleshing out "Data Science" Mind-Map

### ISSUE THREAD

**Issue by 2daysweb** [nikitavoloboev/knowledge-map#688]
I recommend adding three branches to the existing Data Science (specifically coming from the Data Science node!) map:

(1) Math, with sub-branches (linear algebra, multivariate calculus, and statistics)

(2) Programming Languages, with sub-branches (R, Python, SQL)

(3) Machine Learning

For now, I think they can be linked to wikipedia pages on the topics, but I think there are some fantastic answers for what textbooks to use on Quora --- like this one: https://www.quora.com/How-can-I-become-a-data-scientist-1

Hope these help!

**Comment by nikitavoloboev** [comment]
Thank you. It is best to submit feedback under a direct issue for the mind map. [Here](https://github.com/nikitavoloboev/knowledge-map/issues/681) is one for data science.

For points 1, 2 and 3 all three of these topics are main nodes in [main mind map](https://my.mindnode.com/KdeMPbxs8KPixsa5YUq5cphqJnQg81vpHaXcDX2i#-48.5,-680.3,0).

I will go through the quora answer though. 

Thank you a lot for your help.

**Comment by 2daysweb** [comment]
You're welcome. Ahh, got it. I'll be sure to post there from here on out / visit the Main Mind Map.

Thanks!
